lsst-sqre/vo-cutouts

src/vocutouts/uws/jobs.py, src/vocutouts/uws/storage.py
The way timezones were handled wasn't entirely correct, and we
were therefore storing local times in the database and not using
the start time passed to the database worker.  Ensure that we store
UTC everywhere and use the start time we determined.
=> [DM-32386] Fix time handling for job creation, start, end

tests/support/uws.py
If the job start time never turns up, avoid an infinite loop in the
test suite waiting for it.  Cut short the waiting at 5s.
=> Avoid infinite test loop with no job start time

src/vocutouts/uws/storage.py
The underlying asyncpg exception is SerializationError, but
SQLAlchemy catches that and transforms it into a DBAPIError.
Catch that instead to retry transactions that encountered a
conflict due to our isolation level.
Hopefully fixes the recent CI build failures.
=> [DM-33604] Fix async transaction retries

README.rst
DMTN-208 is now published, and the backend is no longer a pipeline
task but instead is image_cutout_backend.
=> [DM-33604] Update README.rst

src/vocutouts/handlers/external.py, src/vocutouts/main.py, tests/handlers/async_test.py, tests/handlers/error_test.py, tests/handlers/external_test.py, tests/handlers/sync_test.py
In the current Science Platform URL scheme, the cutout service is
exposed as /api/cutout.  This previously was done with a rewrite
at the ingress layer to avoid encoding the /api path in the
application, since we anticipate moving the API Aspect to its own
domain name eventually.  However, this means that internal URLs
embedded in result documents are incorrect, particularly affecting
the /api/cutout/capabilities endpoint.
To simplify things, add /api as a prefix to the configured routes.
We can always remove it later if needed.
=> [DM-33604] Change the exposed URL to /api/cutout

.github/workflows/ci.yaml, Dockerfile.worker, scripts/install-worker-packages.sh, scripts/install-worker.sh, scripts/start-worker.sh, src/vocutouts/actors.py, src/vocutouts/workers.py
Build a custom Docker image for the backend worker on top of the
stack Docker image.  Update the Docker image build rules to use
the new GitHub Actions cache mechanism.
Add `store_results` to the actor configuration. For some reason this
doesn't seem necessary for everything to work, but in theory it
should be required to pass results to the callback, and without this
setting Dramatiq issues a warning for every job.
=> [DM-33719] Build a Docker image for the backend worker

CHANGELOG.rst, Dockerfile.worker, scripts/install-worker.sh, src/vocutouts/config.py, src/vocutouts/main.py, src/vocutouts/models/parameters.py, src/vocutouts/policy.py, src/vocutouts/workers.py
Expect a Butler URI as the data ID instead of a bare UUID.  The
CUTOUT_BUTLER_REPOSITORY configuration setting is no longer used.
Instead, the backend worker maintains one instance of a Butler and
corresponding cutout backend per named Butler repository,
determined by parsing the data ID and taking the "host" component
as the name of the Butler repository and the "path" (without the
leading slash) as the UUID.
Also adds some additional backend logging and updates the stack
image used by the cutout worker.
=> [DM-34998] Data IDs are now Butler URIs

CHANGELOG.rst, src/vocutouts/workers.py
The masking, particularly circular masking for a circle cutout,
is very compute-intensive and takes much too long, even if tuned
down to an octagon.  Disable masking for DP0.2.  We can revisit
later with a more performant algorithm.
=> [DM-35058] Disable masking on cutouts

.github/workflows/ci.yaml, CHANGELOG.rst, Dockerfile.worker, setup.cfg, src/vocutouts/workers.py
We originally wanted to raise an error if the cutout stencil didn't
fall within the bounds of the image, but some practical experience
with the Portal has shown that it's better if the stencil clips at
the edge of the image.  This also makes it easier to, for example,
take circular cutouts around a specific object in lots of separate
images that may have different geometries.
=> [DM-35516] Enable clipping of the cutout stencil

Dockerfile.worker
Update the stack container to w_2022_40 (the latest recommended).
=> DM-37516: Bump stack container version

.github/workflows/ci.yaml
Keep the login so that our pulls of the huge stack container are authenticated, but stop uploading containers to Docker Hub.  We only use GitHub Artifact Repository these days.
=> DM-37516: Stop pushing containers to Docker Hub

src/vocutouts/__init__.py
The version was being set from the wrong name.  Use the proper distribution name instead of the Python package name.
=> Fix package version

Makefile, pyproject.toml
Fix the `make run` target for the current tox syntax. Update the mypy configuration and enable the Pydantic mypy plugin.
=> DM-42937: Update run target and mypy configuration

src/vocutouts/main.py
Configure uvicorn to log access messages in a JSON format that can be parsed by Google Log Explorer.
=> DM-42937: Add call to configure_uvicorn_logging

pyproject.toml, src/vocutouts/main.py, src/vocutouts/uws/handlers.py, src/vocutouts/uws/responses.py, tests/uws/conftest.py
Switch to the lifespan context manager, switch to the new TemplateResponse syntax, and switch a few instances of example to examples. Exclude some warnings from the Google libraries.
=> DM-42937: Remove deprecated FastAPI and Starlette constructs

Dockerfile, changelog.d/20240219_145935_rra_DM_42937.md, scripts/install-base-packages.sh, scripts/install-dependency-packages.sh
Use a three-stage build instead of a four-stage build by combining the dependencies image and the install image, since we do not take advantage of their separation for caching. Move git to the install image from the base image, since setuptools_scm only requires it during install.
=> DM-42937: Simplify the Docker configuration

src/vocutouts/config.py
The conversion to the new pydantic-settings module and use of proper timedelta data types for configuration options meant that parsing of number of seconds as strings from environment variables broke. Add a field validator to convert strings to integers so that they'll be parsed correctly.
=> DM-42937: Accept timedelta config values as strings

scripts/install-worker.sh, src/vocutouts/uws/workers.py, src/vocutouts/workers/cutout.py, tests/uws/workers_test.py
Add a separate, minimal UWSWorkerConfig dataclass containing the information needed to construct the backend worker, and modify the worker initialization so that it no longer needs to load the main vo-cutouts Config and thus doesn't depend on pydantic-settings.
Plumb execution_duration in the UWS configuration through to the arq worker configuration so that we at least impose the maximum execution duration limit on worker execution. Supporting the per-job configuration will require more work.
=> DM-44606: Drop pydantic-settings from worker, add timeout

changelog.d/20240607_143229_rra_DM_44720.md, pyproject.toml, requirements/dev.txt, requirements/main.in, requirements/main.txt, scripts/install-worker.sh, src/vocutouts/uws/exceptions.py, src/vocutouts/uws/models.py, src/vocutouts/uws/storage.py, src/vocutouts/workers/cutout.py, tests/uws/exceptions_test.py
Derive `TaskError` from `SlackException` so that eventually we can report unexpected errors to Slack. Rely on `SlackException` to handle serialization support, which is currently on a Safir branch.
Add support for including a traceback of the cause of a `TaskError` exception, and enable that for exceptions from the image cutout backend. Hopefully those exceptions will not contain any security-sensitive information.
=> DM-44720: Improve serialization of task errors

changelog.d/20240607_161544_rra_DM_44720.md, changelog.d/20240607_162437_rra_DM_44720.md, changelog.d/20240610_132302_rra_DM_44720.md, requirements/main.in, requirements/main.txt, scripts/install-worker.sh, src/vocutouts/uws/exceptions.py, src/vocutouts/uws/storage.py, src/vocutouts/uws/workers.py, src/vocutouts/workers/cutout.py, tests/uws/workers_test.py
Configure the UWS arq worker with Slack webhook support, and report unexpected job errors to Slack. Also report any errors updating the database as uncaught exceptions.
=> DM-44720: Report unexpected errors from backend processing

src/vocutouts/models/parameters.py, src/vocutouts/models/stencils.py, src/vocutouts/policy.py, src/vocutouts/uws/policy.py, src/vocutouts/uws/service.py, src/vocutouts/workers/cutout.py, tests/models/parameters_test.py
Pass cutout parameters to the backend as dataclasses instead of dicts and use this to simplify the code. Add a test to ensure that the parameters will be able to be pickled.
Rename access_token to token, following the terminology that we use elsewhere.
=> DM-44763: Take advantage of class serialization

src/vocutouts/cli.py
vo-cutouts doesn't support testing locally, but there was a remnant implementation of vo-cutouts run to start the server. Delete that code.
=> DM-44763: Drop vo-cutouts run command

src/vocutouts/uws/dependencies.py, src/vocutouts/uws/handlers.py
Avoid repeating the same pattern to parse runid out of the POST body by moving it into a reusable dependency. Leave the runid handling for sync GET directly in the sync handler, since only it needs to handle runid as a GET parameter.
=> DM-44763: Move runid handling to a dependency

changelog.d/20240613_185120_rra_DM_44763.md, src/vocutouts/config.py, src/vocutouts/uws/app.py, src/vocutouts/uws/config.py, src/vocutouts/uws/constants.py, src/vocutouts/uws/service.py, src/vocutouts/uws/uwsworker.py, tests/handlers/async_test.py, tests/support/uws.py, tests/uws/job_api_test.py, tests/uws/job_error_test.py, tests/uws/long_polling_test.py, tests/uws/workers_test.py
Unfortunately, there is no way to cancel a sync worker job within arq. ThreadPoolWorker does not offer this functionality, nor does ProcessPoolWorker. We would have to implement our own execution protocol in an external process that we could kill, which would pose cleanup problems.
Reflect this by removing the configuration option for setting a job timeout and forcing the UWS executionduration to 0 by default unless the service supplies a validator for it (in case there are services where the sync backend supports an explicit timeout parameter).
Also remove the vestiges of support for aborting a job, since there is no way to do that either given our worker implementation.
=> DM-44763: Reflect the lack of job cancellation support

src/vocutouts/uws/app.py
Add a comment documenting issues with installing UWS handlers that require careful ordering due to limitations in include_router.
=> DM-44763: Document constraints when adding handlers

src/vocutouts/uws/storage.py
Use the new mypy ParamSpec support to properly type the retry_async_transaction decorator.
=> DM-44763: Fix typing of retry_async_transaction decorator

src/vocutouts/uws/dependencies.py, tests/conftest.py, tests/uws/conftest.py, tests/uws/job_list_test.py
db_session_dependency provided by Safir is by definition a singleton. Previously, the UWS layer used it to talk to the UWS database, but a service using the UWS layer may want its own database connection for other purposes and the UWS layer was monopolizing it. Fix this by creating a separate database engine and session inside the UWS layer.
=> DM-44763: Stop using db_session_dependency in UWS

changelog.d/20240613_201328_rra_DM_44763.md, src/vocutouts/config.py
Use Safir parse_datetime to support human-readable timedelta strings for the lifetime and sync_timeout configuration settings.
=> DM-44763: Support human-readable timedelta strings

src/vocutouts/uws/handlers.py, src/vocutouts/uws/service.py
Unify all of the logging into the UWS service layer and move it out of the handlers. Ensure that the logging includes the username.
=> DM-44763: Move logging to the service layer

changelog.d/20240614_151231_rra_DM_44763.md, src/vocutouts/uws/exceptions.py, src/vocutouts/uws/storage.py, src/vocutouts/uws/uwsworker.py, src/vocutouts/uws/workers.py, src/vocutouts/workers/cutout.py, tests/uws/exceptions_test.py, tests/uws/job_error_test.py, tests/uws/workers_test.py
Separate the exceptions thrown by workers from the code that can translate into UWS job errors and post Slack alerts to reduce the required dependencies for workers. Mark unknown failures as fatal rather than transient, since this is a more conservative guess.
=> DM-44763: Refactor worker exception handling

Dockerfile.worker, changelog.d/20240628_094800_david.irving_DM_44503.md
Upgrade the science pipelines stack to the latest weekly, to include a new version of daf_butler that includes support for a new version of Butler server, which broke backwards compatibility in the REST API we were using previously.
=> DM-44503: Bump science pipelines stack for new Butler

Dockerfile.worker, changelog.d/20240701_153719_david.irving_DM_45088.md
Rolled back the science pipelines version due to a Butler bug that makes the new release unusable.
This reverts commit 48edcf1a4036d0bedd9a40746f05e69c4411ae02.
=> DM-45088: Revert "Bump science pipelines stack for new Butler"

CHANGELOG.md, changelog.d/20240701_153719_david.irving_DM_45088.md, changelog.d/20240705_101725_rra_DM_45132.md, scripts/install-worker-packages.sh
Add a proper version number for the 3.0.0 release and reword some of the changes for additional clarity.
Stop upgrading packages in the worker image since the base image is so old that the package repositories no longer exist.
=> DM-45132: Clean up change log entries, fix worker build

changelog.d/20240708_165945_rra_DM_45138.md, src/vocutouts/uws/app.py, src/vocutouts/uws/constants.py, src/vocutouts/uws/service.py, src/vocutouts/uws/storage.py, src/vocutouts/uws/uwsworker.py, src/vocutouts/uws/workers.py, tests/uws/workers_test.py
Delete all jobs whose destruction date has passed from the UWS database via an arq cron job that runs once per hour.
=> DM-45138: Add an arq cron job to delete expired jobs

changelog.d/20240709_104843_rra_DM_45138.md, src/vocutouts/uws/errors.py
The standard allows a colon after the error code and before the message in plain-text error replies. Make use of this to make the errors a bit more human-readable.
=> DM-45138: Add a colon after the error code

src/vocutouts/models/cutout.py, src/vocutouts/uws/config.py, src/vocutouts/uws/service.py, tests/handlers/async_test.py, tests/models/domain/cutout_test.py, tests/support/uws.py, tests/uws/job_api_test.py
The previous change defined separate worker and API models, but still passed the API model to the backend worker even though it now expected the worker model. Finish the conversion, which requires a bit more typing work and a new required method for ParametersModel. Add tests that the arguments to the backend worker are what we expect them to be.
=> DM-45138: Finish the worker and API model separation

src/vocutouts/models/domain/cutout.py, tests/models/domain/cutout_test.py
This support may end up not being used, but since I wrote it and it seems to work, add it anyway in case it will be useful later.
=> DM-45138: Add deserialization support for astropy types

src/vocutouts/uws/uwsworker.py, tests/uws/workers_test.py
When refactoring, I added a uws_ prefix to the names of the database worker functions but didn't reflect that in the dispatched jobs from the main worker. Fix the latter to also use the uws_ prefix.
=> DM-45138: Fix the names of the UWS worker functions

changelog.d/20240710_144457_rra_DM_45138.md, src/vocutouts/config.py, src/vocutouts/uws/config.py, src/vocutouts/uws/service.py, src/vocutouts/uws/uwsworker.py, tests/handlers/async_test.py, tests/support/uws.py, tests/uws/job_api_test.py, tests/uws/job_error_test.py, tests/uws/long_polling_test.py, tests/uws/workers_test.py
Switch the backend worker to ProcessPoolExecutor and use a really ugly hack to terminate the worker process and rebuild the pool on timeout or job cancellation.
Restore support for execution duration, change the default execution duration back to 10 minutes, and re-add the CUTOUT_TIMEOUT environment variable setting to change the default timeout.
=> DM-45138: Add timeout support

changelog.d/20240710_155859_rra_DM_45138.md, src/vocutouts/config.py
Allow the timedelta configuration parameters to take a number of seconds as a string. Remove the validator for timeout, since it has to be parsed by the cutout worker without using pydantic-settings and therefore must be a simple number of seconds.
=> DM-45138: Restore parsing of seconds as a string

src/vocutouts/config.py
Pydantic's built-in timedelta parsing does not support seconds as a string, so add a validator to handle (and force) that.
=> DM-45138: Fix parsing of string number of seconds for timeout

src/vocutouts/uws/responses.py
Stop assuming the UWS library is installed as files and use the jinja2 PackageLoader instead to retrieve the templates from the package data.
=> DM-45138: Switch to jinja2 PackageLoader

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml
Update the GitHub Actions configuration to match the current fastapi_safir_app template (with some changes that are still pending review). Stop testing with a matrix of Python versions, since services need only support one version. Stop using neophile and instead run make update-deps directly. Use the new tox requirements file instead of manually listing plugins. Use an environment variable to hold the Python version so that it can be changed in fewer places. Fix the way errors from the periodic CI job are reported to avoid a discouraged GitHub Actions construction.
=> DM-45138: Update GitHub Actions configuration

changelog.d/20240715_143650_rra_DM_45138.md, src/vocutouts/uws/results.py, tests/uws/job_api_test.py
If the result URL is an `http` or `https` URL, pass it to the client unchanged.
=> DM-45138: Support pre-signed URLs returned by the backend

src/vocutouts/handlers/external.py, src/vocutouts/uws/app.py, src/vocutouts/uws/handlers.py, src/vocutouts/uws/models.py, src/vocutouts/uws/responses.py, src/vocutouts/uws/service.py, src/vocutouts/uws/storage.py, src/vocutouts/uws/templates/availability.xml, tests/handlers/external_test.py, tests/uws/vosi_test.py
Currently, the /availability route only uses UWS information, so it can be moved entirely into the UWS library. If this needs to be more complicated in the future, we can revisit it.
Use vo-cutouts for the Availability model and XML rendering instead of templating.
=> DM-45138: Move availability handler into UWS library

changelog.d/20240715_155338_rra_DM_45138.md, src/vocutouts/uws/dependencies.py, src/vocutouts/uws/handlers.py, tests/uws/errors_test.py, tests/uws/job_api_test.py
Use a dependency that handles providing phase=RUN in either the query or the POST body, and restore support for the POST body parameter as well as its syntax checks. Add tests to ensure that this doesn't regress.
=> DM-45138: Refactor phase support for async jobs

changelog.d/20240715_164613_rra_DM_45138.md, src/vocutouts/uws/models.py, src/vocutouts/uws/service.py, src/vocutouts/uws/storage.py, src/vocutouts/uws/workers.py, tests/support/uws.py, tests/uws/job_api_test.py
Refactor expiration of jobs to log each job being expired and to abort the job if it is running. Also abort jobs if they are running when the job is deleted, and add a test for deletion of jobs via the POST method rather than the DELETE method.
=> DM-45138: Abort jobs on deletion or expiration

changelog.d/20240715_170552_rra_DM_45138.md, src/vocutouts/config.py, src/vocutouts/uws/app.py, src/vocutouts/uws/constants.py, src/vocutouts/uws/uwsworker.py, src/vocutouts/workers/cutout.py, tests/uws/workers_test.py
Wait for 30 seconds (UWS database workers) or 55 seconds (cutout workers) for jobs to finish before cancelling them. This should match settings on the Kubernetes pod to provide a shutdown grace period.
=> DM-45138: Wait for jobs to finish before cancelling them

src/vocutouts/uws/app.py, src/vocutouts/uws/constants.py, src/vocutouts/uws/uwsworker.py, tests/uws/workers_test.py
To ensure that the worker module is isolated from the rest of the UWS code, move the constant that defines the database worker queue name to the uwsworker module out of constants.
=> DM-45138: Move UWS queue name constant to worker module

src/vocutouts/config.py, tests/handlers/error_test.py
Create a new EnvAsyncPostgresDsn type that modifies the URL based on environment variable settings set by tox-docker, avoiding the need for an explicit validator and making it easier to lift this code into Safir.
Due to a bug in the type system of Pydantic, this does not work in conjunction with the pattern to convert URLs into strings, so undo that change and keep the URL as a Pydantic MultiHostUrl object. This requires explicitly converting it to a string in a few places.
=> DM-45138: Move PostgreSQL URL manipulation into type

src/vocutouts/config.py
Add a type that validates a Redis DSN and substitutes in information from environment variables set by tox-docker if they are present.
=> DM-45138: Move Redis DSN validation into a type

changelog.d/20240819_145310_rra_DM_45824.md, scripts/install-worker.sh, src/vocutouts/workers/cutout.py
Now that saifr-logging is a separate PyPI project that we can depend on independent of the rest of Safir, add a safir-logging dependency to the backend worker and use `configure_logging` to set up logging during module import.
=> DM-45824: Re-add logging configuration for the backend worker

changelog.d/20241021_232057_steliosvoutsinas_DM_47027.md, src/vocutouts/dependencies.py, tests/conftest.py, tests/handlers/sync_test.py
**Summary**
GET & POST list params were not being read correctly, i.e. providing multiple "POS" params. Reason is that we were using 
request.query_params.items() instead of request.query_params.multi_items()
This fix has been tested and does now correctly read in list params.
**Tests**
A test case has been added which introduces a simple route that returns the params that were provided as a json response. 
Not sure if there is a better way to do this?
=> DM-47027: Change get param dependency to correctly parse list params

changelog.d/20241211_181509_rra_DM_47986.md, src/vocutouts/workers/cutout.py
In the backend worker, catch errors from parsing the dataset ID or from initializing Butler. Both can fail due to bad dataset IDs and previously those exceptions weren't being translated into worker exceptions and thus were being reported as uncaught exceptions and generic job failures. Now they will be correctly translated into usage or job failure errors.
=> DM-47986: Catch errors from initializing Butler in worker

README.md, scripts/install-worker.sh, scripts/start-worker.sh, src/vocutouts/workers/cutout.py
Fix the python import to use the new name and no longer attempt to clone and separately install the cutout code.
=> DM-44669: Move image_cutout_backend inside lsst_distrib as dax_images_cutout

src/vocutouts/models/cutout.py, src/vocutouts/models/domain/cutout.py
Use the new `type` keyword instead of `TypeAlias` when creating new types.
=> DM-49075: Use new type syntax for type aliases

src/vocutouts/models/cutout.py, src/vocutouts/models/domain/cutout.py
Annotate overridden methods with `@override`.
=> DM-49075: Use override annotations where appropriate

CHANGELOG.md, ruff-shared.toml
Update the shared Ruff configuration file. Write a change log entry for 4.1.0.
=> DM-49075: Prepare 4.1.0 release

Dockerfile.worker
Update the base image for the cutouts worker to the released v29.1.0 version of the Pipelines stack container.
=> DM-51420: Update to released v29.1.0 Pipelines stack

Dockerfile.worker, changelog.d/20250825_161605_rra_DM_52310.md
Update the backend to the 29.2.0 release of the Science Pipelines, which will hopefully fix a memory leak.
=> DM-52310: Update to the 29.2.0 Science Pipelines container
